version: '3.8'
services:

  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: backend
    image: tsysan/foodgram_backend:v1
    restart: always
    volumes:
      - static_value:/app/static/:rw
      - media_value:/app/media/:rw
    depends_on:
      - db
    env_file:
      - ./.env

  backend-prepare:
    image: tsysan/foodgram_backend:v1
    volumes:
      - static_value:/app/static/:rw
      - media_value:/app/media/:rw
    env_file:
      - ./.env
    command:
      - pre-run

  backend-migrate:
    image: tsysan/foodgram_backend:v1
    restart: on-failure
    depends_on:
      - db
    env_file:
      - ./.env
    command:
      - migrate

  frontend:
    image: tsysan/foodgram_frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/:ro
      - media_value:/var/html/media/:ro
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
    name: static_value
  media_value:
    name: media_value
  postgres_data:
    name: postgres_data